### PR TITLE
Dev

### LINKED ISSUE #11: add list remote assets functionality from CLI
the ability to easily peer at remote asset availablity is currently implemented in the CLI:

https://github.com/databio/refgenie/blob/91a6f6424652689943390cdc0e58a263d0a94738/refgenie/refgenie.py#L380-L387

this is more fundamental... it would be useful, for example, in a pipeline to check if an asset is available in the configured server on-the-fly.

As such, we should move that functionality here, and then call those functions on this object in the CLI.

### LINKED ISSUE #12: add pull asset functionality
Same as #11 but for `pull`

Implemented in CLI here:

https://github.com/databio/refgenie/blob/91a6f6424652689943390cdc0e58a263d0a94738/refgenie/refgenie.py#L297-L374

### PR DESCRIPTION
**Pull request by vreuter**
Close #11 
Close #12

### CODE REVIEW

**Comment by vreuter** [comment]
> great!
> 
> what about the [checksums verification](https://github.com/databio/refgenie/commit/04604009fea007aff744734485ac7b5b97268226) and [archive size display](https://github.com/databio/refgenie/commit/43e8c1e8cec8f8ac0052857ac72eca9a88a7a870)?

What about them? You linked to commits, but the connection is entirely unclear.

**Comment by michalstolarczyk** [comment]
These are not new features, but integral part of the `pull_assets` function that was supposed to be transferred from `refgenie` to `regenconf` which this PR is partially about.

You might started working on this before I committed the changes and that's why these were not included in the code that was transferred.

**Comment by vreuter** [comment]
> These are not new features, but integral part of the `pull_assets` function that was supposed to be transferred from `refgenie` to `regenconf` which this PR is partially about.
> 
> You might started working on this before I committed the changes and that's why these were not included in the code that was transferred.

Yep, that's exactly what happened

**Comment by vreuter** [comment]
Waiting until [support functionality for asset pull](https://github.com/databio/refgenconf/pull/14#issuecomment-497756982) is in place.

**Pull request closed without merging**
