### PR TITLE
Allow list_remote() to work with list of servers. Currently only returning values from first available URL.

### PR DESCRIPTION
**Pull request by blankenberg**
Not entirely clear how should merge strings from different servers together.

### CODE REVIEW

**Comment by stolarczyk** [comment]
thanks for the input and sorry for inconvenience!

This issue has been already solved on `dev` branch in https://github.com/databio/refgenconf/commit/2f8ed13a36551754ec29c0fe464d4241da57caad#diff-26f318e3b2bdd9e87e9bda0170f1f5d7R434-R449

This is how you would use it. The output is a `dict` of  `OrderedDicts`, which you can key by endpoint address the assets where obtained from:
```python
In [3]: rgc.listr()                                                                                                                                                                                       
Out[3]: 
{'http://refgenomes.databio.org/v2/assets': OrderedDict([('hg18',
               ['bismark_bt1_index:default',
                'bismark_bt2_index:default',
                'bowtie2_index:default',
                'bwa_index:default',
                'cellranger_reference:default',
                'fasta.chrom_sizes:default',
                'fasta.fai:default',
                'fasta:default',
                'fasta_txome.chrom_sizes:default',
                'fasta_txome.fai:default',
                'fasta_txome:default',
                'gencode_gtf:default',
                'hisat2_index:default',
                'star_index:default',
                'suffixerator_index.esa:default',
                'tallymer_index.search_file:default',
                'tallymer_index.tindex:default']),
              ('hg18_cdna',
               ['fasta.chrom_sizes:default',
                'fasta.fai:default',
                'fasta:default',
                'hisat2_index:default',
                'kallisto_index:default',
                'salmon_index:default']),
              ('hg19',
               ['bismark_bt1_index:default',
                'bismark_bt2_index:default',
                'bowtie2_index:default',
                'bwa_index:default',
                ...
```

**Comment by nsheff** [comment]
Hi @blankenberg we're addressing several of the issues you raised (and a few others we've found as we try to address them)

we'll probably have an updated version that will be much easier to use shortly

**Comment by blankenberg** [comment]
@nsheff OK, sounds great. I'll poke at something else for a bit.

**Comment by nsheff** [comment]
This update is now released on the master branch. The function name is now `listr` to match the CLI. For multiples servers you'd get multiple entries in the return dict:

```
rgc.listr().keys()
['http://refgenomes.databio.org/v2/assets', 'http://staging.refgenomes.databio.org/v2/assets']
```
Each of these entires is a sub-dict with the available assets

**Pull request closed without merging**
